### ISSUE TITLE
EF.Functions don't seems to be supported

### ISSUE THREAD

**Issue by erwan-joly** [mrahhal/MR.EntityFrameworkCore.KeysetPagination#48] opened 2023-06-25 04:17 UTC
When using EF.Functions the system try to run it client side.
Example:
with npgsql
 ``` .Ascending(i => EF.Functions.FuzzyStringMatchLevenshtein(i.Symbol.ToLower(), name.ToLower()))``` does not work
 
 A normal order by on the query would work fine as it will be translated correctly

**Comment by mrahhal** [comment] 2023-06-25 07:28
What particular error are you getting? "does not work" does not explain enough.

What version are using? Because the example you have is explicitely not supported before v1.3.

**Comment by mrahhal** [comment] 2023-06-25 07:29
The following is assuming you're on the latest version.

There isn't anything in particular to support from this library, as it only generates a query consumed by EF itself. In a keyset query, the generated query not only uses an OrderBy, it also has conditional expressions, so just trying the example you have an OrderBy is not equivalent.

If it's not working, it's probably because EF itself doesn't know how to deal with this in the generated query, which will be something like:
```cs
.OrderBy(i => EF.Functions.FuzzyStringMatchLevenshtein(i.Symbol.ToLower(), name.ToLower()))
.Where(i => EF.Functions.FuzzyStringMatchLevenshtein(i.Symbol.ToLower(), name.ToLower()) > referenceValue)
```

You can try writing something similar to the snippet above to get a simple keyset equivalent query manually, and see if this gives the same error or not.

You'll have to look at the error and see what it's telling you, since it's most likely an error coming from EF itself.

**Comment by erwan-joly** [comment] 2023-06-25 07:56
After checks the query actually runs fine, it throw error on HasPreviousAsync and HasNextAsync
```
A request error occurred!
System.InvalidOperationException: The 'FuzzyStringMatchLevenshtein' method is not supported because the query has switched to client-evaluation. This usually happens when the arguments to the method cannot be translated to server. Rewrite the query to avoid client evaluation of arguments so that method can be translated to server.
   at Microsoft.EntityFrameworkCore.NpgsqlFuzzyStringMatchDbFunctionsExtensions.FuzzyStringMatchLevenshtein(DbFunctions _, String source, String target)
   at lambda_method3891(Closure, Object)
   at MR.EntityFrameworkCore.KeysetPagination.KeysetColumn`2.ObtainValue[TReference](TReference reference)
   at MR.EntityFrameworkCore.KeysetPagination.KeysetFilterPredicateStrategy.GetValues[T](IReadOnlyList`1 columns, Object reference)
   at MR.EntityFrameworkCore.KeysetPagination.KeysetFilterPredicateStrategy.BuildKeysetFilterPredicateExpression[T](IReadOnlyList`1 columns, KeysetPaginationDirection direction, Object reference)
   at MR.EntityFrameworkCore.KeysetPagination.KeysetPaginationExtensions.BuildKeysetFilterPredicateExpression[T](IReadOnlyList`1 columns, KeysetPaginationDirection direction, Object reference)
   at MR.EntityFrameworkCore.KeysetPagination.KeysetPaginationExtensions.HasAsync[T](KeysetPaginationContext`1 context, KeysetPaginationDirection direction, Object reference)
   at MR.EntityFrameworkCore.KeysetPagination.KeysetPaginationExtensions.HasPreviousAsync[T,T2](KeysetPaginationContext`1 context, IReadOnlyList`1 data)
   at MarketRacoon.Database.Cursor.PagedOutputHelper.CreatePagedOutput[TGraphQl,TCursor,TCollectionItem](IQueryable`1 dbQueryable, PagingInput pagingInput, Func`2 buildGraphQlResults, CancellationToken cancellationToken, Action`1 ordering)
   at MarketRacoon.Api.Services.InstrumentService.InstrumentService.ListInstruments(String name, PagingInput input, Nullable`1 marketType, CancellationToken token) in C:\dev\marketracoon\src\MarketRacoon.Api\Services\InstrumentService\InstrumentService.cs:line 73
   at MarketRacoon.Api.GraphQl.InstrumentResolvers.InstrumentResolvers.Instruments(IResolverContext resolverContext, IInstrumentService instrumentService, String filter, PagingInput input, Nullable`1 marketType) in C:\dev\marketracoon\src\MarketRacoon.Api\GraphQl\InstrumentResolvers\InstrumentResolvers.cs:line 28
   at HotChocolate.Resolvers.Expressions.ExpressionHelper.AwaitTaskHelper[T](Task`1 task)
   at HotChocolate.Types.Helpers.FieldMiddlewareCompiler.<>c__DisplayClass9_0.<<CreateResolverMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at HotChocolate.Resolvers.Expressions.Parameters.ServiceHelper.<>c__DisplayClass7_3`1.<<UseResolverServiceInternal>b__5>d.MoveNext()
--- End of stack trace from previous location ---
   at HotChocolate.Resolvers.Expressions.Parameters.ServiceHelper.<>c__DisplayClass7_1`1.<<UseResolverServiceInternal>b__3>d.MoveNext()
--- End of stack trace from previous location ---
   at HotChocolate.Authorization.AuthorizeMiddleware.InvokeAsync(IMiddlewareContext context)
   at HotChocolate.Authorization.AuthorizeDirectiveType.<>c__DisplayClass3_0.<<CreateMiddleware>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MarketRacoon.Api.GraphQl.ValidateArgumentsMiddleware.Invoke(IMiddlewareContext context) in C:\dev\marketracoon\src\MarketRacoon.Api\GraphQl\ValidateArgumentsMiddleware.cs:line 50
   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)
[19:42:23 INF] Executed endpoint 'Hot Chocolate GraphQL Pipeline'
[19:42:23 INF] Request finished HTTP/2 POST https://localhost:5001/graphql application/json 413 - 500 - application/graphql-response+json;+charset=utf-8 1524.5645ms
[19:42:23 ERR] A request error occurred!
System.InvalidOperationException: The 'FuzzyStringMatchLevenshtein' method is not supported because the query has switched to client-evaluation. This usually happens when the arguments to the method cannot be translated to server. Rewrite the query to avoid client evaluation of arguments so that method can be translated to server.
   at Microsoft.EntityFrameworkCore.NpgsqlFuzzyStringMatchDbFunctionsExtensions.FuzzyStringMatchLevenshtein(DbFunctions _, String source, String target)
   at lambda_method3893(Closure, Object)
   at MR.EntityFrameworkCore.KeysetPagination.KeysetColumn`2.ObtainValue[TReference](TReference reference)
   at MR.EntityFrameworkCore.KeysetPagination.KeysetFilterPredicateStrategy.GetValues[T](IReadOnlyList`1 columns, Object reference)
   at MR.EntityFrameworkCore.KeysetPagination.KeysetFilterPredicateStrategy.BuildKeysetFilterPredicateExpression[T](IReadOnlyList`1 columns, KeysetPaginationDirection direction, Object reference)
   at MR.EntityFrameworkCore.KeysetPagination.KeysetPaginationExtensions.BuildKeysetFilterPredicateExpression[T](IReadOnlyList`1 columns, KeysetPaginationDirection direction, Object reference)
   at MR.EntityFrameworkCore.KeysetPagination.KeysetPaginationExtensions.HasAsync[T](KeysetPaginationContext`1 context, KeysetPaginationDirection direction, Object reference)
   at MR.EntityFrameworkCore.KeysetPagination.KeysetPaginationExtensions.HasPreviousAsync[T,T2](KeysetPaginationContext`1 context, IReadOnlyList`1 data)
   at MarketRacoon.Database.Cursor.PagedOutputHelper.CreatePagedOutput[TGraphQl,TCursor,TCollectionItem](IQueryable`1 dbQueryable, PagingInput pagingInput, Func`2 buildGraphQlResults, CancellationToken cancellationToken, Action`1 ordering)
   at MarketRacoon.Api.Services.InstrumentService.InstrumentService.ListInstruments(String name, PagingInput input, Nullable`1 marketType, CancellationToken token) in C:\dev\marketracoon\src\MarketRacoon.Api\Services\InstrumentService\InstrumentService.cs:line 73
   at MarketRacoon.Api.GraphQl.InstrumentResolvers.InstrumentResolvers.Instruments(IResolverContext resolverContext, IInstrumentService instrumentService, String filter, PagingInput input, Nullable`1 marketType) in C:\dev\marketracoon\src\MarketRacoon.Api\GraphQl\InstrumentResolvers\InstrumentResolvers.cs:line 28
   at HotChocolate.Resolvers.Expressions.ExpressionHelper.AwaitTaskHelper[T](Task`1 task)
   at HotChocolate.Types.Helpers.FieldMiddlewareCompiler.<>c__DisplayClass9_0.<<CreateResolverMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at HotChocolate.Resolvers.Expressions.Parameters.ServiceHelper.<>c__DisplayClass7_3`1.<<UseResolverServiceInternal>b__5>d.MoveNext()
--- End of stack trace from previous location ---
   at HotChocolate.Resolvers.Expressions.Parameters.ServiceHelper.<>c__DisplayClass7_1`1.<<UseResolverServiceInternal>b__3>d.MoveNext()
--- End of stack trace from previous location ---
   at HotChocolate.Authorization.AuthorizeMiddleware.InvokeAsync(IMiddlewareContext context)
   at HotChocolate.Authorization.AuthorizeDirectiveType.<>c__DisplayClass3_0.<<CreateMiddleware>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MarketRacoon.Api.GraphQl.ValidateArgumentsMiddleware.Invoke(IMiddlewareContext context) in C:\dev\marketracoon\src\MarketRacoon.Api\GraphQl\ValidateArgumentsMiddleware.cs:line 50
   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)
   ```

**Comment by mrahhal** [comment] 2023-06-25 09:56
> I don't believe the where clause is actually relevant to determine if there is a next or previous ?

It is. It's how keyset works in the general case.

Your expression is just not supported by EF in this particular case so it had to switch to client evaluation. There is nothing that can be done in this library, this is an EF problem.

I can't implement overly complicated logic or logic that doesn't apply to all cases in this library. `HasPreviousAsync`/`HasNextAsync` are meant to be the easy reliable solution here, but they might not be the ideal depending on your situation. You'll have to find an alternative yourself as you mentioned.

I'm closing this as it's clear where the problem is and there's nothing to do in this library, but feel free to add more info or suggestions.

**Closed by mrahhal** 2023-06-25 09:56 UTC
