### ISSUE TITLE
Unable to get the Last page working

### ISSUE THREAD

**Issue by saisworld** [mrahhal/MR.EntityFrameworkCore.KeysetPagination#55] opened 2024-02-05 23:34 UTC
Hi,

I'm trying to get the "Last page" logic working. But it keeps returning the same first page rows. I following of logic mentioned in the documentation to use "backward"

`searchResultsQuery.KeysetPaginate(_keysetBuilderAction, KeysetPaginationDirection.Backward);`

but it keeps returning the same first page results. My query uses multiple joins across multiple tables using EF Core lambda. As EF Core doesnt support `DistinctBy` so I'm using `.GroupBy(z=>z.Id).Select(g=>g.First())` for getting the Distinct rows in my query, is this causing an issue finding the last page ?

**Comment by mrahhal** [comment] 2024-02-06 12:14
Hi. A [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) would really help, as I won't be able to tell just from what you explained. Not sure how `.GroupBy(z=>z.Id).Select(g=>g.First())` factors into this, would need to see the full code in a repro.

Would also help if you try to run the sample in this repo and double check there. If the sample works that means something's wrong with either how you're building this query or maybe there's an edge case in what you're using.

**Comment by mrahhal** [comment] 2024-04-16 09:24
I'm closing this, please reopen if you still have issues.

**Closed by mrahhal** 2024-04-16 09:24 UTC

**Comment by AbdelHamdi** [comment] 2025-01-02 14:23
Facing the same issue, `GroupBy` does not preserve order of records, so it would be problematic to have it before `Take()`, @mrahhal is this a known issue?

**Comment by mrahhal** [comment] 2025-01-02 19:29
No there's no known issue right now. If you could give me a minimal repro as I mentioned above I'd be able to look at and investigate, otherwise not much I can do since I can't reproduce it. Alternatively, you could try to open a PR with a [test](https://github.com/mrahhal/MR.EntityFrameworkCore.KeysetPagination/blob/main/test/MR.EntityFrameworkCore.KeysetPagination.Tests/KeysetPaginationTest.cs) that fails and shows what you're trying to do.

**Comment by mrahhal** [comment] 2025-01-02 19:34
But I don't think there are tests using a `GroupBy` right now, so maybe it's a case I haven't come across. It's probably just EF doing what it usually does, so maybe this is just doesn't play nice with keyset. A test showing exactly the query you're trying to do would still be helpful.
